
name: CI Python Project

on:
  workflow_dispatch:
    inputs:
      TARGET_ENVIRONMENT:
        type: environment
        default: dev

jobs:
  CI_Python_Build:
    runs-on: ubuntu-latest
    environment: ${{ inputs.TARGET_ENVIRONMENT }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'  

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest  

      - name: Package application
        run: |
          mkdir staging
          cp -r your_package_or_script.py staging/  

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.6.2
        with:
          name: Package
          path: staging
